models/EventCenterPrice.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "event_center_price".
 *
 * @property int $id
 * @property int $event_center_id
 * @property string $price
 * @property string $from_day_month
 * @property string $to_day_month
 * @property int $created_by
 * @property string $created_time
 * @property string $updated_time
 * @property int $updated_by
 */
class EventCenterPrice extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'event_center_price';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['event_center_id', 'price', 'created_by', 'created_time'], 'required'],
            [['event_center_id', 'created_by', 'updated_by'], 'integer'],
            [['created_time', 'updated_time'], 'safe'],
            [['price'], 'string', 'max' => 1000],
            [['from_day_month', 'to_day_month'], 'string', 'max' => 50],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'event_center_id' => 'Event Center',
            'price' => 'Price (₦)',
            'from_day_month' => 'From Day Month',
            'to_day_month' => 'To Day Month',
            'created_by' => 'Created By',
            'created_time' => 'Created Time',
            'updated_time' => 'Updated Time',
            'updated_by' => 'Updated By',
        ];
    }
}

controllers/EventCenterController.php
<?php

namespace app\controllers;

use Yii;
use app\models\EventCenter;
use app\models\search\EventCentersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EventCenterController implements the CRUD actions for EventCenter model.
 */
class EventCenterController extends Controller {

    /**
     * {@inheritdoc}
     */
        public function behaviors() {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['index', 'create', 'update', 'delete'],
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return \app\assets\RoleManagement::hasPrivilege($action);
                            //return true;
                        }
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all EventCenter models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new EventCentersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single EventCenter model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new EventCenter model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new EventCenter();

        if ($model->load(Yii::$app->request->post())) {
            $model->created_by = Yii::$app->user->identity->appUserId;
            $model->created_time = date("Y-m-d H:i:s");

            if (!$model->save()) {
                Yii::$app->session->setFlash('error', $model->getErrorSummary(true));
                //print_r($model->getErrors());
                //exit;
            } else {
                Yii::$app->session->setFlash('success', "Saved");
                return $this->redirect(['index']);
            }
        }

        return $this->render('create', [
                    'model' => $model,
        ]);
    }

    /**
     * Updates an existing EventCenter model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->updated_by = Yii::$app->user->identity->appUserId;
            $model->updated_time = date("Y-m-d H:i:s");

            if (!$model->save()) {
                Yii::$app->session->setFlash('error', $model->getErrorSummary(true));
            } else {
                Yii::$app->session->setFlash('success', "Saved");
                return $this->redirect(['index']);
            }
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    /**
     * Deletes an existing EventCenter model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the EventCenter model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return EventCenter the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = EventCenter::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

controllers/EventCenterPriceController.php
<?php

namespace app\controllers;

use Yii;
use app\models\EventCenterPrice;
use app\models\search\EventCenterPriceSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EventCenterPriceController implements the CRUD actions for EventCenterPrice model.
 */
class EventCenterPriceController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['index', 'create', 'update', 'delete'],
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return \app\assets\RoleManagement::hasPrivilege($action);
                            //return true;
                        }
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all EventCenterPrice models.
     * @return mixed
     */
    public function actionIndex($eventCenterId) {

        $eventCenter = $this->findEventCenterModel($eventCenterId);

        $searchModel = new EventCenterPriceSearch();
        $searchModel->event_center_id = $eventCenterId;

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'eventCenter' => $eventCenter,
                    'eventCenterId' => $eventCenterId,
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single EventCenterPrice model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new EventCenterPrice model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new EventCenterPrice();

        $eventCenterId = Yii::$app->request->get("eventCenterId");
        $model->event_center_id = $eventCenterId;
        $eventCenter = $this->findEventCenterModel($eventCenterId);

        if ($model->load(Yii::$app->request->post())) {
            $model->event_center_id = $eventCenterId;
            $model->created_by = Yii::$app->user->identity->appUserId;
            $model->created_time = date("Y-m-d H:i:s");

            if (!$model->save()) {
                Yii::$app->session->setFlash('error', $model->getErrorSummary(true));
            } else {
                Yii::$app->session->setFlash('success', "Saved");
                return $this->redirect(['index?eventCenterId=' . $eventCenterId]);
            }
        }

        return $this->render('create', [
                    'eventCenter' => $eventCenter,
                    'model' => $model,
                    'eventCenterId' => $eventCenterId,
        ]);
    }

    /**
     * Updates an existing EventCenterPrice model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        $eventCenter = $this->findEventCenterModel($model->event_center_id);
        $eventCenterId = $model->event_center_id;
        if ($model->load(Yii::$app->request->post())) {
            $model->updated_by = Yii::$app->user->identity->appUserId;
            $model->updated_time = date("Y-m-d H:i:s");

            if (!$model->save()) {
                Yii::$app->session->setFlash('error', $model->getErrorSummary(true));
            } else {
                Yii::$app->session->setFlash('success', "Saved");
                return $this->redirect(['index?eventCenterId=' . $eventCenterId]);
            }
        }

        return $this->render('update', [
                    'eventCenter' => $eventCenter,
                    'eventCenterId' => $eventCenterId,
                    'model' => $model,
        ]);
    }

    /**
     * Deletes an existing EventCenterPrice model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id) {
        $model = $this->findModel($id);

        $eventCenterId = $model->event_center_id;

        $model->delete();

        return $this->redirect(['index?eventCenterId=' . $eventCenterId]);
    }

    /**
     * Finds the EventCenterPrice model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return EventCenterPrice the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = EventCenterPrice::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    protected function findEventCenterModel($id) {
        if (($model = \app\models\EventCenter::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

views/event-center-price/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\EventCenterPrice */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="col-md-6">

    <?php $form = ActiveForm::begin(); ?>


    <?= $form->field($model, 'price')->textInput(['maxlength' => true, 'type' => 'number']) ?>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'from_day_month')->textInput(['required' => 'required', 'type' => 'date', 'min' => date('m-d-Y'), 'date-format' => 'DD-MM-YYYY']) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'to_day_month')->textInput(['required' => 'required', 'type' => 'date', 'min' => date('m-d-Y'), 'date-format' => 'DD-MM-YYYY']) ?>
        </div>
    </div>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/event-center-price/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\EventCenterPriceSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="event-center-price-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'event_center_id') ?>

    <?= $form->field($model, 'price') ?>

    <?= $form->field($model, 'from_day_month') ?>

    <?= $form->field($model, 'to_day_month') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'created_time') ?>

    <?php // echo $form->field($model, 'updated_time') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/event-center-price/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\EventCenterPrice */
/* @var $eventCenter app\models\EventCenter */

$this->title = 'Create Event Center Price';
$this->params['breadcrumbs'][] = ['label' => $eventCenter->center_name . ' Images', 'url' => ['index?eventCenterId=' . $eventCenter->id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="event-center-price-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'eventCenter' => $eventCenter,
    ]) ?>

</div>

views/event-center-price/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\EventCenterPriceSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Event Center Prices';
$this->params['breadcrumbs'][] = ['label' => 'Event Centers [' . $eventCenter->center_name . ']', 'url' => ['event-center/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="event-center-price-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Event Center Price', ['create?eventCenterId=' . $eventCenterId], ['class' => 'btn btn-success']) ?>
    </p>

    <div class="table-responsive">
        <?=
        GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                //['class' => 'yii\grid\SerialColumn'],
                //'id',
                //'event_center_id',
                'price',
                [
                    'attribute' => 'from_day_month',
                    'format' => 'html',
                    'label' => 'From Date Range',
                    'value' => function ($data) {
                        $date = new DateTime($data['from_day_month']);
                        return $date->format('d - F - Y');
                    },
                ],
                [
                    'attribute' => 'to_day_month',
                    'format' => 'html',
                    'label' => 'To Date Range',
                    'value' => function ($data) {
                        $date = new DateTime($data['to_day_month']);
                        return $date->format('d - F - Y');
                    },
                ],
                //'created_by',
                'created_time',
                'updated_time',
                //'updated_by',
                ['class' => 'yii\grid\ActionColumn'],
            ],
        ]);
        ?>
    </div>
</div>

views/event-center-price/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\EventCenterPrice */

$this->title = 'Update Event Center Price: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => $eventCenter->center_name . ' Images', 'url' => ['index?eventCenterId=' . $eventCenter->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="event-center-price-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model,
        'eventCenter' => $eventCenter,
    ])
    ?>

</div>

views/event-center-price/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\EventCenterPrice */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Event Center Prices', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="event-center-price-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'event_center_id',
            'price',
            'from_day_month',
            'to_day_month',
            'created_by',
            'created_time',
            'updated_time',
            'updated_by',
        ],
    ]) ?>

</div>